// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIDs
{
        public const string achievement_sipper = "CgkIsJG6q7sCEAIQBQ"; // <GPGSID>
        public const string achievement_collector = "CgkIsJG6q7sCEAIQBg"; // <GPGSID>
        public const string achievement_swagatham = "CgkIsJG6q7sCEAIQAg"; // <GPGSID>
        public const string achievement_swiller = "CgkIsJG6q7sCEAIQBw"; // <GPGSID>
        public const string achievement_unlock_bambee = "CgkIsJG6q7sCEAIQAw"; // <GPGSID>
        public const string achievement_unlock_coalbee = "CgkIsJG6q7sCEAIQBA"; // <GPGSID>
        public const string leaderboard_distance_travelled = "CgkIsJG6q7sCEAIQAQ"; // <GPGSID>

}

